import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ubezpieczenia | InsuraLife.pl",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className="">{children}</body>
    </html>
  );
}
